"""
Report Generator: Creates a summary markdown report of pipeline results.
"""

import logging
from collections import Counter, defaultdict
from pathlib import Path

from pipeline.config.settings import EXPORTS_DIR
from pipeline.processors.normalizer import CampSpot

logger = logging.getLogger(__name__)


def generate_report(
    spots: list[CampSpot],
    pre_dedup_count: int = 0,
    output_dir: str | None = None,
    filename: str = "pipeline_report.md",
) -> str:
    """
    Generate a markdown summary report.

    Args:
        spots: Final deduplicated CampSpot list.
        pre_dedup_count: Total count before deduplication.
        output_dir: Output directory.
        filename: Report filename.

    Returns:
        Path to the report file.
    """
    out_dir = Path(output_dir or EXPORTS_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    filepath = out_dir / filename

    total = len(spots)
    source_counts = Counter(s.source for s in spots)
    manager_counts = Counter(s.land_manager for s in spots)
    state_counts = Counter(s.state for s in spots)

    spots_with_photos = sum(1 for s in spots if s.photo_urls)
    total_photos = sum(len(s.photo_urls) for s in spots)
    photo_coverage = (spots_with_photos / total * 100) if total else 0

    spots_with_desc = sum(1 for s in spots if s.description and len(s.description) > 10)
    desc_coverage = (spots_with_desc / total * 100) if total else 0

    spots_with_amenities = sum(1 for s in spots if s.amenities)
    amenity_coverage = (spots_with_amenities / total * 100) if total else 0

    spots_with_name = sum(1 for s in spots if s.name and "unnamed" not in s.name.lower())
    name_coverage = (spots_with_name / total * 100) if total else 0

    lines = [
        "# 🏕️ Free Camping Data Pipeline — Summary Report",
        "",
        "## Overview",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| **Total unique spots** | **{total:,}** |",
        f"| Pre-dedup total | {pre_dedup_count:,} |",
        f"| Duplicates removed | {pre_dedup_count - total:,} |",
        f"| Dedup rate | {((pre_dedup_count - total) / pre_dedup_count * 100) if pre_dedup_count else 0:.1f}% |",
        "",
        "## Source Breakdown",
        "",
        "| Source | Count | % of Total |",
        "|--------|-------|------------|",
    ]

    for source, count in source_counts.most_common():
        pct = count / total * 100 if total else 0
        lines.append(f"| {source.upper()} | {count:,} | {pct:.1f}% |")

    lines.extend([
        "",
        "## Land Manager Breakdown",
        "",
        "| Manager | Count | % of Total |",
        "|---------|-------|------------|",
    ])

    for manager, count in manager_counts.most_common():
        pct = count / total * 100 if total else 0
        lines.append(f"| {manager} | {count:,} | {pct:.1f}% |")

    lines.extend([
        "",
        "## Data Quality",
        "",
        f"| Metric | Coverage |",
        f"|--------|----------|",
        f"| Named spots (not 'Unnamed') | {name_coverage:.1f}% ({spots_with_name:,}/{total:,}) |",
        f"| Has description (>10 chars) | {desc_coverage:.1f}% ({spots_with_desc:,}/{total:,}) |",
        f"| Has amenities data | {amenity_coverage:.1f}% ({spots_with_amenities:,}/{total:,}) |",
        f"| **Has photos** | **{photo_coverage:.1f}%** ({spots_with_photos:,}/{total:,}) |",
        f"| Total photo URLs | {total_photos:,} |",
    ])

    lines.extend([
        "",
        "## Coverage by State",
        "",
        "| State | Count | Has Photos |",
        "|-------|-------|------------|",
    ])

    # State counts sorted by count descending
    state_photo_counts: dict[str, int] = defaultdict(int)
    for s in spots:
        if s.photo_urls:
            state_photo_counts[s.state] += 1

    for state, count in sorted(state_counts.items(), key=lambda x: -x[1]):
        photo_count = state_photo_counts.get(state, 0)
        lines.append(f"| {state} | {count:,} | {photo_count:,} |")

    lines.extend([
        "",
        "---",
        "",
        "*Generated by CampRoo Free Camping Data Pipeline*",
    ])

    report_text = "\n".join(lines)

    with open(filepath, "w") as f:
        f.write(report_text)

    logger.info(f"Generated report: {filepath}")
    return str(filepath)
